### ISSUE TITLE
Error in visualize result(GIF)

### ISSUE THREAD

**Issue by megz2020** [muellerdo/kits19.MIScnn#3]
when i run cross_validation i get error python numpy ValueError: operands could not be broadcast together with shapes
when i trace error i think it's in overlay_segmentation function

**Comment by muellerdo** [comment]
Hey megz2020,

this repository is outdated. 
Try using the MIScnn version from the official repository. https://github.com/frankkramer-lab/MIScnn

You will also find an example for the KiTS19 data set under 'examples' in the wiki or in the readme.

It is working much more flawless and intuitive, but also result into way higher performance :)

Greetings,
Dominik
